# Jekyll settings
destination: _site
source: src
permalink: pretty
markdown: rdiscount

# Blog settings
authorname: Christian Specht
gravatar_url: http://www.gravatar.com/avatar/6f807629c5f3765f28c61b1271552dc9?s=
