# Jekyll settings
destination: _site
source: src
permalink: pretty
markdown: kramdown
timezone: "Europe/Berlin"
commitid: abcdefghijklmn
buildnumber: 123

# Blog settings
name: Christian Specht
authorname: Christian Specht
description: Personal site of Christian Specht, software developer from Kerpen, Germany.
url: https://christianspecht.de
collections:
- projects

# production mode (will be overwritten by _config_dev.yml in dev mode)
environment: prod

# feed URLs
rss_url: /feed/index.xml
atom_url: /feed/atom/index.xml

# URL replacements for feeds
feed_linkurl_find: href="/
feed_linkurl_replace: href="https://christianspecht.de/
feed_imgurl_find: src="/
feed_imgurl_replace: src="https://christianspecht.de/