# Jekyll settings
destination: _site
source: src
permalink: pretty
markdown: rdiscount

# Blog settings
name: Christian Specht
authorname: Christian Specht
description: Personal site of Christian Specht, software developer from Kerpen, Germany.
url: http://christianspecht.de
gravatar_url: http://www.gravatar.com/avatar/6f807629c5f3765f28c61b1271552dc9?s=

# production mode (will be overwritten by _config_dev.yml in dev mode)
environment: prod

# URL replacements for feeds
feed_linkurl_find: href="/
feed_linkurl_replace: href="http://christianspecht.de/
feed_imgurl_find: src="/
feed_imgurl_replace: src="http://christianspecht.de/