baseURL = 'https://christianspecht.de'
languageCode = 'en-us'
title = 'Christian Specht'

contentDir = "src"
publishDir = "../_site"

theme = "custom-bootstrap" 

[params]
commitid = "abcdefghi"
buildnumber = "123456"

