baseURL = 'https://christianspecht.de'
languageCode = 'en-us'
title = 'Christian Specht'

publishDir = "../_site"

theme = "custom-bootstrap" 

[params]
commitid = "abcdefghi"
buildnumber = "123456"

[permalinks]
posts = '/:year/:month/:day/:slug/'
